### ISSUE TITLE
Subsystem: ADC

### ISSUE THREAD

**Issue by zebra6** [zebra6/tux_2.0#3]
This is a parent ticket for the ADC subsystem, create new tickets for individual tasks.

Areas to investigate:
- Virtual Load-Cell
- SPI? To Pi
- Driver - open-source?
- Timer-driven updates - 100 ms updates (10 Hz)?
- Periodic Sampling
- Add more to this description as necessary

**Comment by beardedtrogon** [comment]
Just realized, we should be grabbing X-bit ADC values not floats right? Can this be changed? Python writing is pretty slow and I want to be able to have periodic writes to the text file. Want to practice with data that makes sense

**Comment by zebra6** [comment]
The ADC driver will probably convert whatever the LBC is reading to a value and put that in the device tree.  We are writing 100x a second now, you should be able to verify with tail -f.  The way it is functioning now is as accurate as I can think without actually having and ADC to emulate.

**Comment by beardedtrogon** [comment]
36.803620457976145

^ that's an output i'm seeing from the virtual driver.

Isn't that too accurate? We want a 12 bit resolution at most.

**Comment by zebra6** [comment]
Python truncates the values when it prints, not when it writes.  So we can adjust the resolution if you want, but the number format will be the same.  Also how _n_-bits translates into a float is not a constant operation, and will depend on the ADC we select.

**Comment by beardedtrogon** [comment]
Moving to Bitrix
