### ISSUE TITLE
Subsystem: WiFi/Radio

### ISSUE THREAD

**Issue by zebra6** [zebra6/tux_2.0#4]
This is a parent ticket for the radio communications subsystem, create new tickets for individual tasks.

Areas to investigate:
- On-board (assuming RPi3)?
- Serial Comm w/ Pi
- Connectivity to Toughpad
- Add more items to this description as necessary

**Comment by beardedtrogon** [comment]
Start looking into this

**Comment by beardedtrogon** [comment]
Ad-hoc network established with Toughpad. WPA2 needed here?

**Comment by beardedtrogon** [comment]
Ability to switch between Ad-hoc and DHCP client to router. Issue with WPA2/Enterprise

**Comment by beardedtrogon** [comment]
Moving to Bitrix
