### ISSUE TITLE
Subsystem: SD Card and Logging

### ISSUE THREAD

**Issue by zebra6** [zebra6/tux_2.0#6]
This is a parent ticket for the logging subsystem, create new tickets for individual tasks.

Areas to investigate:
- Python Script
- Determine File Format
- Logging Processes - Raw?
- Check delta from last record to avoid writing useless data
- Add more to this description as necessary

**Comment by beardedtrogon** [comment]
Subsystem Priority #1 for Aadu

**Comment by beardedtrogon** [comment]
Python script

**Comment by beardedtrogon** [comment]
Moving to Bitrix
